services:
  postgres:
    image: postgres
    container_name: db_c
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
